[package]
authors = ["Nisan <bknisan@gmail.com>"]
edition = "2018"
name = "Rustification"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
